"""jamoa tavsifi tarjimasi

Revision ID: d682fc1d411d
Revises: e401bc8cda84
Create Date: 2026-07-28 15:21:49.593134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd682fc1d411d'
down_revision: Union[str, None] = 'e401bc8cda84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_uz', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('description_uz')

    # ### end Alembic commands ###
