"""teams jadvali

Revision ID: e401bc8cda84
Revises: 377acb784ec9
Create Date: 2026-07-28 09:22:22.721273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e401bc8cda84'
down_revision: Union[str, None] = '377acb784ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('league_name', sa.String(), nullable=True),
    sa.Column('badge', sa.String(), nullable=True),
    sa.Column('stadium', sa.String(), nullable=True),
    sa.Column('stadium_capacity', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('founded', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_league_id'), ['league_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_slug'))
        batch_op.drop_index(batch_op.f('ix_teams_name'))
        batch_op.drop_index(batch_op.f('ix_teams_league_id'))
        batch_op.drop_index(batch_op.f('ix_teams_id'))

    op.drop_table('teams')
    # ### end Alembic commands ###
