"""boshlangich sxema

Loyihaning birinchi migratsiyasi — mavjud modellardan (matches, news, users)
avtomatik yaratilgan. Alembicdan oldin sxema `Base.metadata.create_all` orqali
tuzilardi, shuning uchun eski bazalar bu revizyada `stamp` qilinadi
(app/core/migrations.py ga qarang).

Revision ID: 377acb784ec9
Revises:
Create Date: 2026-07-27 18:39:04.125517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '377acb784ec9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('league_name', sa.String(), nullable=True),
    sa.Column('home_team_name', sa.String(), nullable=True),
    sa.Column('away_team_name', sa.String(), nullable=True),
    sa.Column('home_team_logo', sa.String(), nullable=True),
    sa.Column('away_team_logo', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('score_home', sa.Integer(), nullable=True),
    sa.Column('score_away', sa.Integer(), nullable=True),
    sa.Column('match_time', sa.DateTime(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('lineups', sa.JSON(), nullable=True),
    sa.Column('timeline', sa.JSON(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('ai_preview', sa.Text(), nullable=True),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('win_probability', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_away_team_name'), ['away_team_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_home_team_name'), ['home_team_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_league_id'), ['league_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_league_name'), ['league_name'], unique=False)

    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_news_title'), ['title'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('favorite_team', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_title'))
        batch_op.drop_index(batch_op.f('ix_news_slug'))
        batch_op.drop_index(batch_op.f('ix_news_id'))
        batch_op.drop_index(batch_op.f('ix_news_created_at'))

    op.drop_table('news')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_league_name'))
        batch_op.drop_index(batch_op.f('ix_matches_league_id'))
        batch_op.drop_index(batch_op.f('ix_matches_id'))
        batch_op.drop_index(batch_op.f('ix_matches_home_team_name'))
        batch_op.drop_index(batch_op.f('ix_matches_away_team_name'))

    op.drop_table('matches')
    # ### end Alembic commands ###
